export const searchPlaceholder = {
    TRADEMARK: "请输入商标名称、申请号、申请人等",
    TRADE_PATENT: "请输入专利名称",
};

export const cascadeData = new Map([
    [
        "city",
        [
            {
                value: "11",
                label: "北京",
                children: [{ value: "110101", label: "北京" }],
            },
            {
                value: "31",
                label: "上海",
                children: [{ value: "310101", label: "上海" }],
            },
            {
                value: "12",
                label: "天津",
                children: [{ value: "120101", label: "天津" }],
            },
            {
                value: "44",
                label: "广东",
                children: [
                    { value: "4400", label: "广东" },
                    { value: "4401", label: "广州" },
                    { value: "4402", label: "韶关" },
                    { value: "4403", label: "深圳" },
                    { value: "4404", label: "珠海" },
                    { value: "4405", label: "汕头" },
                    { value: "4406", label: "佛山" },
                    { value: "4407", label: "江门" },
                    { value: "4408", label: "湛江" },
                    { value: "4409", label: "茂名" },
                    { value: "4412", label: "肇庆" },
                    { value: "4413", label: "惠州" },
                    { value: "4414", label: "梅州" },
                    { value: "4415", label: "汕尾" },
                    { value: "4416", label: "河源" },
                    { value: "4417", label: "阳江" },
                    { value: "4418", label: "清远" },
                    { value: "4419", label: "东莞" },
                    { value: "4420", label: "中山" },
                    { value: "4451", label: "潮州" },
                    { value: "4452", label: "揭阳" },
                    { value: "4453", label: "云浮" },
                ],
            },
            {
                value: "45",
                label: "广西",
                children: [
                    { value: "4500", label: "广西" },
                    { value: "4501", label: "南宁" },
                    { value: "4502", label: "柳州" },
                    { value: "4503", label: "桂林" },
                    { value: "4504", label: "梧州" },
                    { value: "4505", label: "北海" },
                    { value: "4506", label: "防城港" },
                    { value: "4507", label: "钦州" },
                    { value: "4508", label: "贵港" },
                    { value: "4509", label: "玉林" },
                    { value: "4510", label: "百色" },
                    { value: "4511", label: "贺州" },
                    { value: "4512", label: "河池" },
                    { value: "4513", label: "来宾" },
                    { value: "4514", label: "崇左" },
                ],
            },
            {
                value: "13",
                label: "河北",
                children: [
                    { value: "1300", label: "河北" },
                    { value: "1301", label: "石家庄" },
                    { value: "1302", label: "唐山" },
                    { value: "1303", label: "秦皇岛" },
                    { value: "1304", label: "邯郸" },
                    { value: "1305", label: "邢台" },
                    { value: "1306", label: "保定" },
                    { value: "1307", label: "张家口" },
                    { value: "1308", label: "承德" },
                    { value: "1309", label: "沧州" },
                    { value: "1310", label: "廊坊" },
                    { value: "1311", label: "衡水" },
                ],
            },
            {
                value: "14",
                label: "山西",
                children: [
                    { value: "1400", label: "山西" },
                    { value: "1401", label: "太原" },
                    { value: "1402", label: "大同" },
                    { value: "1403", label: "阳泉" },
                    { value: "1404", label: "长治" },
                    { value: "1405", label: "晋城" },
                    { value: "1406", label: "朔州" },
                    { value: "1407", label: "晋中" },
                    { value: "1408", label: "运城" },
                    { value: "1409", label: "忻州" },
                    { value: "1410", label: "临汾" },
                    { value: "1411", label: "吕梁" },
                ],
            },
            {
                value: "15",
                label: "内蒙古",
                children: [
                    { value: "1500", label: "内蒙" },
                    { value: "1501", label: "呼和浩特" },
                    { value: "1502", label: "包头" },
                    { value: "1503", label: "乌海" },
                    { value: "1504", label: "赤峰" },
                    { value: "1505", label: "通辽" },
                    { value: "1506", label: "鄂尔多斯" },
                    { value: "1507", label: "呼伦贝尔" },
                    { value: "1508", label: "巴彦淖尔" },
                    { value: "1509", label: "乌兰察布" },
                    { value: "1522", label: "兴安盟" },
                    { value: "1525", label: "锡林郭勒盟" },
                    { value: "1529", label: "阿拉善盟" },
                ],
            },
            {
                value: "21",
                label: "辽宁",
                children: [
                    { value: "2100", label: "辽宁" },
                    { value: "2101", label: "沈阳" },
                    { value: "2102", label: "大连" },
                    { value: "2103", label: "鞍山" },
                    { value: "2104", label: "抚顺" },
                    { value: "2105", label: "本溪" },
                    { value: "2106", label: "丹东" },
                    { value: "2107", label: "锦州" },
                    { value: "2108", label: "营口" },
                    { value: "2109", label: "阜新" },
                    { value: "2110", label: "辽阳" },
                    { value: "2111", label: "盘锦" },
                    { value: "2112", label: "铁岭" },
                    { value: "2113", label: "朝阳" },
                    { value: "2114", label: "葫芦岛" },
                ],
            },
            {
                value: "22",
                label: "吉林",
                children: [
                    { value: "2202", label: "吉林" },
                    { value: "2202", label: "吉林" },
                    { value: "2203", label: "四平" },
                    { value: "2204", label: "辽源" },
                    { value: "2205", label: "通化" },
                    { value: "2206", label: "白山" },
                    { value: "2207", label: "松原" },
                    { value: "2208", label: "白城" },
                    { value: "2224", label: "延边朝鲜族自治州" },
                ],
            },
            {
                value: "23",
                label: "黑龙江",
                children: [
                    { value: "2300", label: "黑龙江" },
                    { value: "2301", label: "哈尔滨" },
                    { value: "2302", label: "齐齐哈尔" },
                    { value: "2303", label: "鸡西" },
                    { value: "2304", label: "鹤岗" },
                    { value: "2305", label: "双鸭山" },
                    { value: "2306", label: "大庆" },
                    { value: "2307", label: "伊春" },
                    { value: "2308", label: "佳木斯" },
                    { value: "2309", label: "七台河" },
                    { value: "2310", label: "牡丹江" },
                    { value: "2311", label: "黑河" },
                    { value: "2312", label: "绥化" },
                    { value: "2327", label: "大兴安岭地区" },
                ],
            },
            {
                value: "32",
                label: "江苏",
                children: [
                    { value: "3200", label: "江苏" },
                    { value: "3201", label: "南京" },
                    { value: "3202", label: "无锡" },
                    { value: "3203", label: "徐州" },
                    { value: "3204", label: "常州" },
                    { value: "3205", label: "苏州" },
                    { value: "3206", label: "南通" },
                    { value: "3207", label: "连云港" },
                    { value: "3208", label: "淮安" },
                    { value: "3209", label: "盐城" },
                    { value: "3210", label: "扬州" },
                    { value: "3211", label: "镇江" },
                    { value: "3212", label: "泰州" },
                    { value: "3213", label: "宿迁" },
                ],
            },
            {
                value: "33",
                label: "浙江",
                children: [
                    { value: "3300", label: "浙江" },
                    { value: "3301", label: "杭州" },
                    { value: "3302", label: "宁波" },
                    { value: "3303", label: "温州" },
                    { value: "3304", label: "嘉兴" },
                    { value: "3305", label: "湖州" },
                    { value: "3306", label: "绍兴" },
                    { value: "3307", label: "金华" },
                    { value: "3308", label: "衢州" },
                    { value: "3309", label: "舟山" },
                    { value: "3310", label: "台州" },
                    { value: "3311", label: "丽水" },
                ],
            },
            {
                value: "34",
                label: "安徽",
                children: [
                    { value: "3400", label: "安徽" },
                    { value: "3401", label: "合肥" },
                    { value: "3402", label: "芜湖" },
                    { value: "3403", label: "蚌埠" },
                    { value: "3404", label: "淮南" },
                    { value: "3405", label: "马鞍山" },
                    { value: "3406", label: "淮北" },
                    { value: "3407", label: "铜陵" },
                    { value: "3408", label: "安庆" },
                    { value: "3410", label: "黄山" },
                    { value: "3411", label: "滁州" },
                    { value: "3412", label: "阜阳" },
                    { value: "3413", label: "宿州" },
                    { value: "3415", label: "六安" },
                    { value: "3416", label: "亳州" },
                    { value: "3417", label: "池州" },
                    { value: "3418", label: "宣城" },
                ],
            },
            {
                value: "35",
                label: "福建",
                children: [
                    { value: "3500", label: "福建" },
                    { value: "3501", label: "福州" },
                    { value: "3502", label: "厦门" },
                    { value: "3503", label: "莆田" },
                    { value: "3504", label: "三明" },
                    { value: "3505", label: "泉州" },
                    { value: "3506", label: "漳州" },
                    { value: "3507", label: "南平" },
                    { value: "3508", label: "龙岩" },
                    { value: "3509", label: "宁德" },
                ],
            },
            {
                value: "36",
                label: "江西",
                children: [
                    { value: "3600", label: "江西" },
                    { value: "3601", label: "南昌" },
                    { value: "3602", label: "景德镇" },
                    { value: "3603", label: "萍乡" },
                    { value: "3604", label: "九江" },
                    { value: "3605", label: "新余" },
                    { value: "3606", label: "鹰潭" },
                    { value: "3607", label: "赣州" },
                    { value: "3608", label: "吉安" },
                    { value: "3609", label: "宜春" },
                    { value: "3610", label: "抚州" },
                    { value: "3611", label: "上饶" },
                ],
            },
            {
                value: "37",
                label: "山东",
                children: [
                    { value: "3700", label: "山东" },
                    { value: "3701", label: "济南" },
                    { value: "3702", label: "青岛" },
                    { value: "3703", label: "淄博" },
                    { value: "3704", label: "枣庄" },
                    { value: "3705", label: "东营" },
                    { value: "3706", label: "烟台" },
                    { value: "3707", label: "潍坊" },
                    { value: "3708", label: "济宁" },
                    { value: "3709", label: "泰安" },
                    { value: "3710", label: "威海" },
                    { value: "3711", label: "日照" },
                    { value: "3712", label: "莱芜" },
                    { value: "3713", label: "临沂" },
                    { value: "3714", label: "德州" },
                    { value: "3715", label: "聊城" },
                    { value: "3716", label: "滨州" },
                    { value: "3717", label: "菏泽" },
                ],
            },
            {
                value: "41",
                label: "河南",
                children: [
                    { value: "4100", label: "河南" },
                    { value: "4101", label: "郑州" },
                    { value: "4102", label: "开封" },
                    { value: "4103", label: "洛阳" },
                    { value: "4104", label: "平顶山" },
                    { value: "4105", label: "安阳" },
                    { value: "4106", label: "鹤壁" },
                    { value: "4107", label: "新乡" },
                    { value: "4108", label: "焦作" },
                    { value: "4109", label: "濮阳" },
                    { value: "4110", label: "许昌" },
                    { value: "4111", label: "漯河" },
                    { value: "4112", label: "三门峡" },
                    { value: "4113", label: "南阳" },
                    { value: "4114", label: "商丘" },
                    { value: "4115", label: "信阳" },
                    { value: "4116", label: "周口" },
                    { value: "4117", label: "驻马店" },
                    { value: "419001", label: "济源" },
                ],
            },
            {
                value: "42",
                label: "湖北",
                children: [
                    { value: "4200", label: "湖北" },
                    { value: "4201", label: "武汉" },
                    { value: "4202", label: "黄石" },
                    { value: "4203", label: "十堰" },
                    { value: "4205", label: "宜昌" },
                    { value: "4206", label: "襄阳" },
                    { value: "4207", label: "鄂州" },
                    { value: "4208", label: "荆门" },
                    { value: "4209", label: "孝感" },
                    { value: "4210", label: "荆州" },
                    { value: "4211", label: "黄冈" },
                    { value: "4212", label: "咸宁" },
                    { value: "4213", label: "随州" },
                    { value: "4228", label: "恩施土家族苗族自治州" },
                    { value: "429004", label: "仙桃" },
                    { value: "429005", label: "潜江" },
                    { value: "429006", label: "天门" },
                    { value: "429021", label: "神农架林" },
                ],
            },
            {
                value: "43",
                label: "湖南",
                children: [
                    { value: "4300", label: "湖南" },
                    { value: "4301", label: "长沙" },
                    { value: "4302", label: "株洲" },
                    { value: "4303", label: "湘潭" },
                    { value: "4304", label: "衡阳" },
                    { value: "4305", label: "邵阳" },
                    { value: "4306", label: "岳阳" },
                    { value: "4307", label: "常德" },
                    { value: "4308", label: "张家界" },
                    { value: "4309", label: "益阳" },
                    { value: "4310", label: "郴州" },
                    { value: "4311", label: "永州" },
                    { value: "4312", label: "怀化" },
                    { value: "4313", label: "娄底" },
                    { value: "4331", label: "湘西土家族苗族自治州" },
                ],
            },
            {
                value: "46",
                label: "海南",
                children: [
                    { value: "4600", label: "海南" },
                    { value: "4601", label: "海口" },
                    { value: "4602", label: "三亚" },
                    { value: "4603", label: "三沙" },
                    { value: "4604", label: "儋州" },
                    { value: "469001", label: "五指山" },
                    { value: "469002", label: "琼海" },
                    { value: "469005", label: "文昌" },
                    { value: "469006", label: "万宁" },
                    { value: "469007", label: "东方" },
                    { value: "469021", label: "定安县" },
                    { value: "469022", label: "屯昌县" },
                    { value: "469023", label: "澄迈县" },
                    { value: "469024", label: "临高县" },
                    { value: "469025", label: "白沙黎族自治县" },
                    { value: "469026", label: "昌江黎族自治县" },
                    { value: "469027", label: "乐东黎族自治县" },
                    { value: "469028", label: "陵水黎族自治县" },
                    { value: "469029", label: "保亭黎族苗族自治县" },
                    { value: "469030", label: "琼中黎族苗族自治县" },
                ],
            },
            {
                value: "50",
                label: "重庆",
                children: [
                    { value: "500100", label: "重庆" },
                    { value: "500101", label: "万州" },
                    { value: "500102", label: "涪陵" },
                    { value: "500103", label: "渝中" },
                    { value: "500104", label: "大渡口" },
                    { value: "500105", label: "江北" },
                    { value: "500106", label: "沙坪坝" },
                    { value: "500107", label: "九龙坡" },
                    { value: "500108", label: "南岸" },
                    { value: "500109", label: "北碚" },
                    { value: "500110", label: "綦江" },
                    { value: "500111", label: "大足" },
                    { value: "500112", label: "渝北" },
                    { value: "500113", label: "巴南" },
                    { value: "500114", label: "黔江" },
                    { value: "500115", label: "长寿" },
                    { value: "500116", label: "江津" },
                    { value: "500117", label: "合川" },
                    { value: "500118", label: "永川" },
                    { value: "500119", label: "南川" },
                    { value: "500120", label: "璧山" },
                    { value: "500151", label: "铜梁" },
                    { value: "500152", label: "潼南" },
                    { value: "500153", label: "荣昌" },
                    { value: "500154", label: "开州" },
                    { value: "500155", label: "梁平" },
                    { value: "500156", label: "武隆" },
                    { value: "500229", label: "城口县" },
                    { value: "500230", label: "丰都县" },
                    { value: "500231", label: "垫江县" },
                    { value: "500233", label: "忠县" },
                    { value: "500235", label: "云阳县" },
                    { value: "500236", label: "奉节县" },
                    { value: "500237", label: "巫山县" },
                    { value: "500238", label: "巫溪县" },
                    { value: "500240", label: "石柱土家族自治县" },
                    { value: "500241", label: "秀山土家族苗族自治县" },
                    { value: "500242", label: "酉阳土家族苗族自治县" },
                    { value: "500243", label: "彭水苗族土家族自治县" },
                ],
            },
            {
                value: "51",
                label: "四川",
                children: [
                    { value: "5100", label: "四川" },
                    { value: "5101", label: "成都" },
                    { value: "5103", label: "自贡" },
                    { value: "5104", label: "攀枝花" },
                    { value: "5105", label: "泸州" },
                    { value: "5106", label: "德阳" },
                    { value: "5107", label: "绵阳" },
                    { value: "5108", label: "广元" },
                    { value: "5109", label: "遂宁" },
                    { value: "5110", label: "内江" },
                    { value: "5111", label: "乐山" },
                    { value: "5113", label: "南充" },
                    { value: "5114", label: "眉山" },
                    { value: "5115", label: "宜宾" },
                    { value: "5116", label: "广安" },
                    { value: "5117", label: "达州" },
                    { value: "5118", label: "雅安" },
                    { value: "5119", label: "巴中" },
                    { value: "5120", label: "资阳" },
                    { value: "5132", label: "阿坝藏族羌族自治州" },
                    { value: "5133", label: "甘孜藏族自治州" },
                    { value: "5134", label: "凉山彝族自治州" },
                ],
            },
            {
                value: "52",
                label: "贵州",
                children: [
                    { value: "5200", label: "贵州" },
                    { value: "5201", label: "贵阳" },
                    { value: "5202", label: "六盘水" },
                    { value: "5203", label: "遵义" },
                    { value: "5204", label: "安顺" },
                    { value: "5205", label: "毕节" },
                    { value: "5206", label: "铜仁" },
                    { value: "5223", label: "黔西南布依族苗族自治州" },
                    { value: "5226", label: "黔东南苗族侗族自治州" },
                    { value: "5227", label: "黔南布依族苗族自治州" },
                ],
            },
            {
                value: "53",
                label: "云南",
                children: [
                    { value: "5300", label: "云南" },
                    { value: "5301", label: "昆明" },
                    { value: "5303", label: "曲靖" },
                    { value: "5304", label: "玉溪" },
                    { value: "5305", label: "保山" },
                    { value: "5306", label: "昭通" },
                    { value: "5307", label: "丽江" },
                    { value: "5308", label: "普洱" },
                    { value: "5309", label: "临沧" },
                    { value: "5323", label: "楚雄彝族自治州" },
                    { value: "5325", label: "红河哈尼族彝族自治州" },
                    { value: "5326", label: "文山壮族苗族自治州" },
                    { value: "5328", label: "西双版纳傣族自治州" },
                    { value: "5329", label: "大理白族自治州" },
                    { value: "5331", label: "德宏傣族景颇族自治州" },
                    { value: "5333", label: "怒江傈僳族自治州" },
                    { value: "5334", label: "迪庆藏族自治州" },
                ],
            },
            {
                value: "54",
                label: "西藏",
                children: [
                    { value: "5400", label: "西藏" },
                    { value: "5401", label: "拉萨" },
                    { value: "5402", label: "日喀则" },
                    { value: "5403", label: "昌都" },
                    { value: "5404", label: "林芝" },
                    { value: "5405", label: "山南" },
                    { value: "5406", label: "那曲" },
                    { value: "5425", label: "阿里地" },
                ],
            },
            {
                value: "61",
                label: "陕西",
                children: [
                    { value: "6100", label: "陕西" },
                    { value: "6101", label: "西安" },
                    { value: "6102", label: "铜川" },
                    { value: "6103", label: "宝鸡" },
                    { value: "6104", label: "咸阳" },
                    { value: "6105", label: "渭南" },
                    { value: "6106", label: "延安" },
                    { value: "6107", label: "汉中" },
                    { value: "6108", label: "榆林" },
                    { value: "6109", label: "安康" },
                    { value: "6110", label: "商洛" },
                ],
            },
            {
                value: "62",
                label: "甘肃",
                children: [
                    { value: "6201", label: "兰州" },
                    { value: "6202", label: "嘉峪关" },
                    { value: "6203", label: "金昌" },
                    { value: "6204", label: "白银" },
                    { value: "6205", label: "天水" },
                    { value: "6206", label: "武威" },
                    { value: "6207", label: "张掖" },
                    { value: "6208", label: "平凉" },
                    { value: "6209", label: "酒泉" },
                    { value: "6210", label: "庆阳" },
                    { value: "6211", label: "定西" },
                    { value: "6212", label: "陇南" },
                    { value: "6229", label: "临夏回族自治州" },
                    { value: "6230", label: "甘南藏族自治州" },
                ],
            },
            {
                value: "63",
                label: "青海",
                children: [
                    { value: "6300", label: "青海" },
                    { value: "6301", label: "西宁" },
                    { value: "6302", label: "海东" },
                    { value: "6322", label: "海北藏族自治州" },
                    { value: "6323", label: "黄南藏族自治州" },
                    { value: "6325", label: "海南藏族自治州" },
                    { value: "6326", label: "果洛藏族自治州" },
                    { value: "6327", label: "玉树藏族自治州" },
                    { value: "6328", label: "海西蒙古族藏族自治州" },
                ],
            },
            {
                value: "64",
                label: "宁夏回族自治",
                children: [
                    { value: "6401", label: "银川" },
                    { value: "6402", label: "石嘴山" },
                    { value: "6403", label: "吴忠" },
                    { value: "6404", label: "固原" },
                    { value: "6405", label: "中卫" },
                ],
            },
            {
                value: "65",
                label: "新疆",
                children: [
                    { value: "6500", label: "新疆" },
                    { value: "6501", label: "乌鲁木齐" },
                    { value: "6502", label: "克拉玛依" },
                    { value: "6504", label: "吐鲁番" },
                    { value: "6505", label: "哈密" },
                    { value: "6523", label: "昌吉回族自治州" },
                    { value: "6527", label: "博尔塔拉蒙古自治州" },
                    { value: "6528", label: "巴音郭楞蒙古自治州" },
                    { value: "6529", label: "阿克苏地" },
                    { value: "6530", label: "克孜勒苏柯尔克孜自治州" },
                    { value: "6531", label: "喀什地" },
                    { value: "6532", label: "和田地" },
                    { value: "6540", label: "伊犁哈萨克自治州" },
                    { value: "6542", label: "塔城地" },
                    { value: "6543", label: "阿勒泰地" },
                    { value: "659001", label: "石河子" },
                    { value: "659002", label: "阿拉尔" },
                    { value: "659003", label: "图木舒克" },
                    { value: "659004", label: "五家渠" },
                    { value: "659006", label: "铁门关" },
                ],
            },
            {
                value: "67",
                label: "澳门",
                children: [{ value: "6700", label: "澳门特别行政区" }],
            },
            {
                value: "68",
                label: "香港",
                children: [{ value: "6800", label: "香港特别行政区" }],
            },
            {
                value: "69",
                label: "台湾",
                children: [{ value: "6900", label: "台湾" }],
            },
        ],
    ],
    [
        "kind",
        [
            {
                value: "1",
                label: "许可类",
                children: [
                    {
                        value: "1-1",
                        label: "投资管理",
                    },
                    {
                        value: "1-2",
                        label: "金融",
                    },
                    {
                        value: "1-3",
                        label: "资产",
                    },
                    {
                        value: "1-4",
                        label: "融资租赁",
                    },
                    {
                        value: "1-5",
                        label: "医疗器械",
                    },
                    {
                        value: "1-6",
                        label: "人力资源",
                    },
                    {
                        value: "1-7",
                        label: "食品",
                    },
                    {
                        value: "1-8",
                        label: "劳务派遣",
                    },
                ],
            },
            {
                value: "2",
                label: "科技类",
                children: [
                    {
                        value: "2-1",
                        label: "网络科技",
                    },
                    {
                        value: "2-2",
                        label: "电子商务",
                    },
                    {
                        value: "2-3",
                        label: "信息技术",
                    },
                    {
                        value: "2-4",
                        label: "游戏",
                    },
                    {
                        value: "2-5",
                        label: "电子",
                    },
                    {
                        value: "2-6",
                        label: "软件",
                    },
                    {
                        value: "2-7",
                        label: "新材料",
                    },
                    {
                        value: "2-8",
                        label: "生物科技",
                    },
                    {
                        value: "2-9",
                        label: "教育科技",
                    },
                    {
                        value: "2-10",
                        label: "环保科技",
                    },
                    {
                        value: "2-11",
                        label: "信息科技",
                    },
                ],
            },
            {
                value: "3",
                label: "服务类",
                children: [
                    {
                        value: "3-1",
                        label: "广告",
                    },
                    {
                        value: "3-2",
                        label: "文化传媒",
                    },
                    {
                        value: "3-3",
                        label: "建筑装潢",
                    },
                    {
                        value: "3-4",
                        label: "设计",
                    },
                    {
                        value: "3-5",
                        label: "美容美发",
                    },
                    {
                        value: "3-6",
                        label: "房地产中介",
                    },
                    {
                        value: "3-7",
                        label: "物业管理",
                    },
                    {
                        value: "3-8",
                        label: "商务咨询",
                    },
                    {
                        value: "3-9",
                        label: "企业管理",
                    },
                ],
            },
            {
                value: "4",
                label: "其他",
                children: [
                    {
                        value: "4-1",
                        label: "贸易",
                    },
                    {
                        value: "4-2",
                        label: "实业",
                    },
                    {
                        value: "4-3",
                        label: "制造",
                    },
                    {
                        value: "4-4",
                        label: "服饰",
                    },
                    {
                        value: "4-5",
                        label: "化妆品",
                    },
                    {
                        value: "4-6",
                        label: "工程",
                    },
                    {
                        value: "4-7",
                        label: "农业",
                    },
                    {
                        value: "4-8",
                        label: "餐饮管理",
                    },
                    {
                        value: "4-9",
                        label: "物流",
                    },
                ],
            },
        ],
    ],
    [
        "type",
        [
            {
                label: "有限公司",
                value: 1,
            },
            {
                label: "有限责任公司",
                value: 2,
            },
            {
                label: "股份公司",
                value: 3,
            },
            {
                label: "股份有限公司",
                value: 4,
            },
            {
                label: "集团有限公司",
                value: 5,
            },
            {
                label: "(集团)有限公司",
                value: 6,
            },
            {
                label: "集团股份有限公司",
                value: 7,
            },
            {
                label: "(集团)股份有限公司",
                value: 8,
            },
            {
                label: "合伙企业(普通合伙)",
                value: 9,
            },
            {
                label: "合伙企业(特殊普通合伙)",
                value: 10,
            },
            {
                label: "合伙企业(有限合伙)",
                value: 11,
            },
        ],
    ],
]);
